export const ALL_FIELDS = 'allFields';
export const SEARCH_FIELDS = {
  ANONYMOUSID: 'anonymousId',
  BILLINGADDRESS: 'billingAddress',
  BUSINESSUNIT: 'businessUnit',
  CARTSTATE: 'cartState',
  COUNTRY: 'country',
  CREATEDAT: 'createdAt',
  CREATEDBY: 'createdBy',
  CUSTOM: 'custom',
  CUSTOMLINEITEMS: 'customLineItems',
  CUSTOMEREMAIL: 'customerEmail',
  CUSTOMERGROUP: 'customerGroup',
  CUSTOMERID: 'customerId',
  DELETEDAYSAFTERLASTMODIFICATION: 'deleteDaysAfterLastModification',
  DISCOUNTCODES: 'discountCodes',
  ID: 'id',
  INVENTORYMODE: 'inventoryMode',
  ITEMSHIPPINGADDRESSES: 'itemShippingAddresses',
  KEY: 'key',
  LASTMODIFIEDAT: 'lastModifiedAt',
  LASTMODIFIEDBY: 'lastModifiedBy',
  LINEITEMS: 'lineItems',
  LOCALE: 'locale',
  PAYMENTINFO: 'paymentInfo',
  SHIPPING: 'shipping',
  SHIPPINGADDRESS: 'shippingAddress',
  SHIPPINGCUSTOMFIELDS: 'shippingCustomFields',
  SHIPPINGINFO: 'shippingInfo',
  SHIPPINGRATEINPUT: 'shippingRateInput',
  STORE: 'store',
  TAXCALCULATIONMODE: 'taxCalculationMode',
  TAXMODE: 'taxMode',
  TAXROUNDINGMODE: 'taxRoundingMode',
  TAXEDPRICE: 'taxedPrice',
  TOTALPRICE: 'totalPrice',
  VERSION: 'version',
};
