export const TYPES = {
  String: 'String',
  LocalizedString: 'LocalizedString',
  Number: 'Number',
  Boolean: 'Boolean',
  Money: 'Money',
  Date: 'Date',
  Time: 'Time',
  DateTime: 'DateTime',
  Enum: 'Enum',
  LocalizedEnum: 'LocalizedEnum',
  Object: 'Object',
  Reference: 'Reference',
};

export const REFERENCE_BY = {
  Key: 'key',
  Id: 'id',
};

export const RESOURCE_TYPES = [
  'address',
  'asset',
  'approval-flow',
  'associate-role',
  'business-unit',
  'cart-discount',
  'category',
  'channel',
  'customer',
  'customer-group',
  'custom-line-item',
  'discount-code',
  'inventory-entry',
  'line-item',
  'order',
  'order-edit',
  'order-delivery',
  'order-parcel',
  'order-return-item',
  'payment',
  'payment-interface-interaction',
  'product-price',
  'product-selection',
  'quote',
  'shipping',
  'shipping-method',
  'shopping-list',
  'shopping-list-text-line-item',
  'standalone-price',
  'store',
  'transaction',
];
