name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    env:
      CLOUD_IDENTIFIER: gcp-eu
      CUSTOM_APPLICATION_ID: TODO
      APPLICATION_URL: https://your_app_hostname.com
      INITIAL_PROJECT_KEY: todo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: './visualizer/.nvmrc'
          cache: 'npm'
          cache-dependency-path: './visualizer/package-lock.json'

      - name: Install dependencies
        working-directory: ./visualizer
        run: npm ci

      - name: Building packages
        working-directory: ./visualizer
        run: npm run build

      - name: Run tests
        working-directory: ./visualizer
        run: npm run test
        env:
          CI: true
